Added tests for collection-utils methods replaceelementAt and length
AndcultureCode/AndcultureCode.JavaScript.Core pull request #40
Opened 2020-09-02 18:00 UTC by SaidShah

- [x] Related GitHub issue(s) linked in PR description
- [x] Destination branch merged, built and tested with your changes
- [x] Code formatted and follows best practices and patterns
- [x] Code builds cleanly (no _additional_ warnings or errors)
- [x] Manually tested
- [x] Automated tests are passing
- [x] No _decreases_ in automated test coverage
- [x] Documentation updated (readme, docs, comments, etc.)
- [x] Localization: No hard-coded error messages in code files (_minimally_ in string constants)

2020-09-02 19:48 UTC, brandongregoryscott requested changes
Left some feedback for refactoring - let me know when it's ready to re-review @SaidShah !

2020-09-02 19:48 UTC, brandongregoryscott commented on src/utilities/collection-utils.test.ts
> +            expect(result).toBe(2);
Instead of hardcoding the 2 here, I would update it to be `array.length`

2020-09-02 19:48 UTC, brandongregoryscott commented on src/utilities/collection-utils.test.ts
> +    describe("#length", () => {
I'm not sure how many other describe blocks are like this, but would you mind wrapping each one in a region block with the method name being tested?

```TS
    // -----------------------------------------------------------------------------------------
    // #region length
    // -----------------------------------------------------------------------------------------
    
    // #endregion length
```

2020-09-02 19:48 UTC, brandongregoryscott commented on src/utilities/collection-utils.test.ts
> +            expect(result).toBe(2);
Same here - reference `list.count` (or whatever the appropriate field/method is for retrieving a list's size)

2020-09-02 19:48 UTC, brandongregoryscott commented on src/utilities/collection-utils.test.ts
> +            expect(equals).toBe(true);
Had to double check what method was under test here - adding the region around each method's respective `describe()` block would help 👍

2020-09-03 17:26 UTC, SaidShah commented
@brandongregoryscott I have made the changes you requested. Please take a look when you get a chance.

2020-09-03 17:58 UTC, brandongregoryscott commented
Thanks for making those updates @SaidShah! Great work.

2020-09-03 18:00 UTC, brandongregoryscott commented
One other thing - I forgot to mention you didn't actually list the original issue in the description. Just make sure you're tagging the issue when you're going through the checklist next time 👍 thanks!

2020-09-03 18:01 UTC, merged